# Generated by Django 4.2 on 2023-08-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="categorias_id",
        ),
        migrations.AddField(
            model_name="evento",
            name="categorias",
            field=models.ManyToManyField(to="core.categoria"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto representativa do evento (JPEG, até 5MB, 1200x1200px)",
                null=True,
                upload_to="event_photos/",
            ),
        ),
    ]
