# Generated by Django 4.2 on 2023-08-28 00:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_evento_categorias_id_evento_categorias_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="categorias",
            new_name="categorias_id",
        ),
    ]
