# Generated by Django 4.2 on 2023-09-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_categorias_evento_categorias_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="pref_categorias",
        ),
        migrations.AddField(
            model_name="usuario",
            name="pref_categorias",
            field=models.ManyToManyField(
                help_text="Preferências de categorias em lista", to="core.categoria"
            ),
        ),
    ]
