# Generated by Django 4.2 on 2023-10-21 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_usuario_pref_categorias_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="usuario_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.usuario"
            ),
        ),
    ]
