# Generated by Django 4.2 on 2023-11-22 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_avaliacao_usuario_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="usuario_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.usuario"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="avaliacao",
            unique_together={("usuario_id", "evento_id")},
        ),
    ]
